DROP TABLE MEMBERS;
DROP TABLE NOTICEBOARD;

DROP SEQUENCE MEMBERS_MNO_SEQ;
DROP SEQUENCE NOTICEBOARD_BNO_SEQ;

CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL
,   ID VARCHAR2(50) NOT NULL
,   EMAIL VARCHAR2(100) NOT NULL
,   PWD VARCHAR2(100) NOT NULL
,   MNAME VARCHAR2(50) NOT NULL
,   NICKNAME VARCHAR2(50) NOT NULL
,   CRE_DATE DATE NOT NULL
,   MOD_DATE DATE NOT NULL
);

COMMENT ON TABLE MEMBERS IS '회원기본정보';

COMMENT ON COLUMN MEMBERS.MNO IS '회원번호';
COMMENT ON COLUMN MEMBERS.ID IS '아이디';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.PWD IS '암호';
COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
COMMENT ON COLUMN MEMBERS.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '가입일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '마지막암호변경일';

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);
ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_ID_UK UNIQUE (ID);
ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_UK UNIQUE (EMAIL);

CREATE SEQUENCE MEMBERS_MNO_SEQ
INCREMENT BY 1
    START WITH 1;
    
    
CREATE TABLE NOTICEBOARD(
    BNO NUMBER,
    EMAIL VARCHAR2(100),
    SUBJECT VARCHAR2(100),
    WRITER VARCHAR2(100),
    CONTENT VARCHAR2(100),
    CRE_DATE DATE,
    MOD_DATE DATE,
    VIEW_COUNT NUMBER
);
COMMENT ON TABLE NOTICEBOARD IS '게시판정보';

COMMENT ON COLUMN NOTICEBOARD.BNO IS '글번호';
COMMENT ON COLUMN NOTICEBOARD.EMAIL IS '이메일';
COMMENT ON COLUMN NOTICEBOARD.SUBJECT IS '제목';
COMMENT ON COLUMN NOTICEBOARD.WRITER IS '글쓴이';
COMMENT ON COLUMN NOTICEBOARD.CONTENT IS '글내용';
COMMENT ON COLUMN NOTICEBOARD.CRE_DATE IS '작성일';
COMMENT ON COLUMN NOTICEBOARD.MOD_DATE IS '수정일';
COMMENT ON COLUMN NOTICEBOARD.VIEW_COUNT IS '조회수';

CREATE SEQUENCE NOTICEBOARD_BNO_SEQ
INCREMENT BY 1
    START WITH 1;

ALTER TABLE NOTICEBOARD
ADD CONSTRAINT NOTICEBOARD_BNO_PK PRIMARY KEY(BNO);

INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, '123', '123@test.com', '123', '관리자'
    , '관리자닉', SYSDATE, SYSDATE);

COMMIT;

SELECT *
FROM NOTICEBOARD;

UPDATE NOTICEBOARD
SET SUBJECT='수정', CONTENT='변경'
WHERE BNO = 11;
