DROP TABLE MEMBERS;
DROP TABLE NOTICEBOARD;

DROP SEQUENCE MEMBERS_MNO_SEQ;
DROP SEQUENCE NOTICEBOARD_BNO_SEQ;

CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL
,   ID VARCHAR2(50) NOT NULL
,   EMAIL VARCHAR2(100) NOT NULL
,   PWD VARCHAR2(100) NOT NULL
,   MNAME VARCHAR2(50) NOT NULL
,   NICKNAME VARCHAR2(50) NOT NULL
,   CRE_DATE DATE NOT NULL
,   MOD_DATE DATE NOT NULL
);

COMMENT ON TABLE MEMBERS IS '회원기본정보';

COMMENT ON COLUMN MEMBERS.MNO IS '회원번호';
COMMENT ON COLUMN MEMBERS.ID IS '아이디';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.PWD IS '암호';
COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
COMMENT ON COLUMN MEMBERS.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '가입일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '마지막암호변경일';

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);
ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_ID_UK UNIQUE (ID);
ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_UK UNIQUE (EMAIL);

CREATE SEQUENCE MEMBERS_MNO_SEQ
INCREMENT BY 1
    START WITH 1;
    
    
CREATE TABLE BOARD(
    BNO NUMBER,
    EMAIL VARCHAR2(100) NOT NULL,
    SUBJECT VARCHAR2(100) NOT NULL,
    WRITER VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0
);
COMMENT ON TABLE BOARD IS '게시판정보';

COMMENT ON COLUMN BOARD.BNO IS '글번호';
COMMENT ON COLUMN BOARD.EMAIL IS '이메일';
COMMENT ON COLUMN BOARD.SUBJECT IS '제목';
COMMENT ON COLUMN BOARD.WRITER IS '글쓴이';
COMMENT ON COLUMN BOARD.CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.CRE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.MOD_DATE IS '수정일';
COMMENT ON COLUMN BOARD.VIEW_COUNT IS '조회수';

CREATE SEQUENCE BOARD_BNO_SEQ
INCREMENT BY 1
    START WITH 1;

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_BNO_PK PRIMARY KEY(BNO);

INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, '1', 'ldh@test.com', '123', '이동현'
    , '동현', SYSDATE, SYSDATE);
INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, '2', 'lyb@test.com', '123', '이영빈'
    , '영빈', SYSDATE, SYSDATE);
INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, '3', 'sdh@test.com', '123', '손다예'
    , '다예', SYSDATE, SYSDATE);
    
COMMIT;

